name: Feature Request
description: Suggest an idea or enhancement for Templify
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case - how would this feature be used?
      placeholder: |
        When generating invoices, I need to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: If applicable, provide an example of how you'd like to use this feature
      render: csharp
      placeholder: |
        var processor = new DocumentTemplateProcessor();
        processor.EnableFeatureX();

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with Templify's goal of Word document templating
          required: true
        - label: I would be willing to contribute a PR for this feature
          required: false
