name: Question
description: Ask a question about using Templify
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        Before asking, please check:
        - [Documentation](https://triasdev.github.io/templify/)
        - [FAQ](https://triasdev.github.io/templify/articles/FAQ.html)
        - [Examples](https://github.com/TriasDev/templify/tree/main/TriasDev.Templify/Examples.md)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to accomplish
      placeholder: I'm trying to generate reports with...
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already attempted?
      placeholder: I tried using... but...

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, share relevant code
      render: csharp

  - type: input
    id: version
    attributes:
      label: Templify Version
      placeholder: e.g., 1.0.0

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues
          required: true
